default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spotted_development
  username: davidyurek
  password:

test:
  <<: *default
  database: spotted_test
  username: davidyurek
  password:

production:
  <<: *default
  database: spotted_production
  username: spotted
  password: <%= ENV['SPOTTED_DATABASE_PASSWORD'] %>
