default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spotted_development

test:
  <<: *default
  database: spotted_test

production:
   <<: *default
   database: spotted_production
   username: spotted
   password: <%= ENV['SPOTTED_DATABASE_PASSWORD'] %>
